
apiVersion: 1

datasources:
  - name: MongoDB
    type: marcusolsson-mongodb-datasource
    access: proxy
    jsonData:
      mongodb_url: mongodb://mongodb:27017
      database: iot
      collection: sensor_data
    editable: true
